### ISSUE TITLE
Don't want to be a drag, but...

### ISSUE THREAD

**Issue by 0b1kn00b** [asciiascetic/farcek#1]
https://github.com/sledorze/Parsex/

could use some love.

**Comment by asciiascetic** [comment]
Haha. 

I made farcek to be simple (for me) to use.  Don't worry that parser-combinator domain real estate is being filled up - the space is infinitely large. 

Farcek is slow and naive and perfect for me.

That said, I'll look into it.

**Comment by 0b1kn00b** [comment]
:) Makes no odds, really. Check ometa and ohm for some really interesting algorithms / dsl's, and the idea of pushing a parser-generator in the header (Alan Kay). Not sure if there is a way to unite LR packrat parser and parser combinators. Plus, I never worked out the rules for aysynchronous stream parsing with all the other goodies, EOF vs chunk end requires some jiggery pokery.
Plenty of real estate, not so many tenants.
